baseURL = 'https://yunhaimath.com/'
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = 'en-us'
title = 'Yunhai Xiang'
theme = 'texify'

[pagination]
pagerSize = 5


[taxonomies]
tags = "tags"
categories = "categories"


[params]
title="Yunhai Xiang"
author = "Yunhai Xiang"
description = ""
footnote = """
Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a> | 
Theme <a class=link href=https://github.com/michaelneuper/hugo-texify3 target=_blank rel=noopener>TeXify3</a>
"""
customCSS = []
customJS = []
dateFormat = "2 January 2006"
emphasisWithDots = true
toc = true
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = true
numberedSubtitles = true
