baseURL = 'https://yunhaimath.com/'
enableGitInfo = true
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = 'en-us'
title = 'Yunhai Xiang'
theme = 'texify'
ignoreLogs = ['warning-goldmark-raw-html']


[markup]
defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.parser]
      [markup.goldmark.parser.attribute]
        block = true
        title = true
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          inline = [["$", "$"], ["\\(", "\\)"]]
          block  = [["$$", "$$"], ["\\[", "\\]"]]

  [markup.highlight]
  codeFences = true
  guessSyntax = true
  noClasses = false
  style = "gruvbox"
          
[taxonomies]
tags = "tags"
categories = "categories"

[minify]
  disableHTML = false

[minify.tdewolff.html]
  keepWhitespace = true

[author]
name = "Yunhai Xiang"

[params]
title = "Yunhai Xiang"
author = "Yunhai Xiang"
description = ""
footnote = """
Powered by  <a class=link href=https://gohugo.io target=_blank rel=noopener>Hugo</a>
"""
customCSS = []
customJS = []
dateFormat = "January 2, 2006"
emphasisWithDots = true
toc = true
rootFontSize = "105%"
math = true
enableDuckDuckGoSearchBox = false
numberedSubtitles = true
enableEmoji = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'
