[module]
  [module.hugoVersion]
    min = "0.138.0"

[markup]
defaultMarkdownHandler = "goldmark"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      typographer = false
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          inline = [["$", "$"], ["\\(", "\\)"]]
          block  = [["$$", "$$"], ["\\[", "\\]"]]